bin/helpers: add helpers useful for Go coverage collection
Signed-off-by: Simon Deziel <simon.deziel@canonical.com>

diff --git a/bin/helpers b/bin/helpers
--- a/bin/helpers
+++ b/bin/helpers
@@ -451,6 +451,51 @@ teardown_swap() {
     rm "${LXD_CI_SWAPFILE}"
 }
 
+# Returns true if Go coverage collection is enabled (GOCOVERDIR is set).
+coverage_enabled() {
+  [ -n "${GOCOVERDIR:-}" ]
+}
+
+# Setup instance to collect coverage data from running Go binaries from inside the instance.
+# If coverage is not enabled, this is a no-op.
+# If the instance is a VM, the lxd-agent will be instrumented too.
+# Note: incompatible with `migration.stateful=true` instances.
+setup_instance_gocoverage() {
+  coverage_enabled || return 0
+
+  local instance="${1}"
+  local project="${2:-}"
+
+  echo "==> Setting up Go coverage gathering inside the ${instance} (${project:-"-"}) instance"
+
+  # Mount the host's GOCOVERDIR into the instance.
+  lxc config device add "${instance}" gocoverdir disk source="${GOCOVERDIR}" path="${GOCOVERDIR}" --project "${project}"
+
+  # The GOCOVERDIR variable is set for use by test binaries.
+  lxc config set "${instance}" environment.GOCOVERDIR="${GOCOVERDIR}" --project "${project}"
+
+  # The lxd-agent is only relevant for VMs.
+  if [ "$(lxc list --project "${project}" -f csv -c t name="${instance}")" != "VIRTUAL-MACHINE" ]; then
+    return 0
+  fi
+
+  # The GOCOVERDIR variable is passed to lxd-agent via a systemd drop-in.
+  lxc file push --quiet --create-dirs --project "${project}" - "${instance}"/etc/systemd/system/lxd-agent.service.d/env.conf << EOF
+[Service]
+Environment="GOCOVERDIR=${GOCOVERDIR}"
+EOF
+  lxc exec "${instance}" --project "${project}" -- systemctl daemon-reload
+
+  # Restarting lxd-agent is expected to abruptly terminate the lxc exec session,
+  # so a failure is possible and harmless.
+  lxc exec "${instance}" --project "${project}" -- systemctl restart --no-block lxd-agent.service || true
+
+  # Restarting the lxd-agent isn't instantaneous, so wait for it to be ready again.
+  waitInstanceReady "${instance}" "${project}"
+
+  # Give lxd-agent a moment to start up properly.
+  sleep 1
+}
 
 # cleanup: report if the test passed or not and return the appropriate return code.
 cleanup() {
