bin/helpers: run any extra cleanup function
Signed-off-by: Simon Deziel <simon.deziel@canonical.com>

diff --git a/bin/helpers b/bin/helpers
--- a/bin/helpers
+++ b/bin/helpers
@@ -152,6 +152,11 @@ runsMinimumKernel() (
 
 # cleanup: report if the test passed or not and return the appropriate return code.
 cleanup() {
+    # Run any extra cleanup function
+    if command -v extra_cleanup > /dev/null; then
+      extra_cleanup || true
+    fi
+
     echo ""
     if [ "${FAIL}" = "1" ]; then
         echo "Test failed"
