tests/container: add bpf token tests
Tests for https://github.com/canonical/lxd/pull/15009

Signed-off-by: Alexander Mikhalitsyn <aleksandr.mikhalitsyn@canonical.com>

diff --git a/tests/container b/tests/container
--- a/tests/container
+++ b/tests/container
@@ -163,7 +163,7 @@ EOF
 done
 unset WARNING_PREFIX
 
-IMAGE="ubuntu-minimal-daily:24.04"
+IMAGE="${TEST_IMG:-ubuntu-minimal-daily:24.04}"
 
 echo "==> check that we can mount devpts and procfs in unprivileged container"
 lxc launch "${IMAGE}" u1
@@ -206,6 +206,33 @@ wait $!
 echo "==> Ensure aliased image won't launch with VM flag set"
 lxc image alias create containeralias "$(lxc config get c1 volatile.base_image)"
 ! lxc launch containeralias c2 --vm || false
+
+echo "==> Test unprivileged BPF delegation"
+if ! { runsMinimumKernel 6.9 && hasNeededAPIExtension container_bpf_delegation; }; then
+    # check that we fail container to start if kernel has no support for bpf token
+    if hasNeededAPIExtension container_bpf_delegation; then
+        lxc delete -f c1
+        lxc init "${IMAGE}" c1
+        lxc config set c1 security.delegate_bpf=true
+        ! lxc start c1 || false
+    fi
+
+    echo "Skipping unprivileged container bpf delegation test as the kernel is too old or LXD support missing"
+else
+    lxc delete -f c1
+    lxc init "${IMAGE}" c1
+
+    lxc config set c1 security.delegate_bpf=true
+    lxc config set c1 security.delegate_bpf.prog_types=socket_filter
+    lxc config set c1 security.delegate_bpf.attach_types=cgroup_inet_ingress
+    lxc config set c1 security.delegate_bpf.cmd_types=prog_load:map_create
+    lxc config set c1 security.delegate_bpf.map_types=ringbuf
+
+    lxc start c1
+    waitInstanceBooted c1
+
+    lxc exec c1 -- grep -F "delegate_cmds=map_create:prog_load,delegate_maps=ringbuf,delegate_progs=socket_filter,delegate_attachs=cgroup_inet_ingress" /proc/self/mountinfo
+fi
 
 # Cleanup
 lxc delete -f c1
