tests/*: drop test-lxd- prefix from test scripts
Signed-off-by: Simon Deziel <simon.deziel@canonical.com>

diff --git a/tests/docker b/tests/docker
--- a/tests/docker
+++ b/tests/docker
@@ -1,11 +1,49 @@
 #!/bin/sh -eux
 CNAME="docker-$(uuidgen)"
 
+waitSnapdSeed() (
+  set +x
+  for i in $(seq 60); do # Wait up to 60s.
+    if systemctl show snapd.seeded.service --value --property SubState | grep -qx exited; then
+      return 0 # Success.
+    fi
+
+    sleep 1
+  done
+
+  echo "snapd not seeded after ${i}s"
+  return 1 # Failed.
+)
+
 cleanup() {
-    lxc delete --force "${CNAME}"
+    echo ""
+    if [ "${FAIL}" = "1" ]; then
+        echo "Test failed"
+        exit 1
+    fi
+
+    echo "Test passed"
+    exit 0
 }
 
+FAIL=1
 trap cleanup EXIT HUP INT TERM
+
+# Wait for snapd seeding
+waitSnapdSeed
+
+# Install LXD
+while [ -e /usr/bin/lxd ]; do
+    apt-get remove --purge --yes lxd lxd-client lxcfs liblxc1
+done
+apt-get remove --purge cloud-init --yes
+snap remove lxd || true
+snap install lxd --channel=latest/edge
+apt-get install --no-install-recommends --yes jq
+lxd waitready --timeout=300
+
+lxd init --auto
+set -x
 
 # Create the container
 lxc launch images:ubuntu/bionic "${CNAME}" -c security.nesting=true "$@"
@@ -14,11 +52,7 @@ lxc launch images:ubuntu/bionic "${CNAME}" -c security.nesting=true "$@"
 cat << EOF
 #!/bin/sh
 # Wait for network
-while :; do
-    ping -W1 -c1 linuxcontainers.org >/dev/null 2>&1 && break
-    sleep 1
-done
-
+sleep 10
 set -eux
 
 # Install distro docker
@@ -53,3 +87,6 @@ docker info
 docker run hello-world
 EOF
 ) | lxc exec "${CNAME}" -- sh -eux
+
+lxc delete --force "${CNAME}"
+FAIL=0
