tests/gpu-vm: tweak test
Signed-off-by: Simon Deziel <simon.deziel@canonical.com>

diff --git a/tests/gpu-vm b/tests/gpu-vm
--- a/tests/gpu-vm
+++ b/tests/gpu-vm
@@ -2,28 +2,30 @@
 set -eu
 
 waitSnapdSeed() (
-  set +x
-  for i in $(seq 60); do # Wait up to 60s.
-    if systemctl show snapd.seeded.service --value --property SubState | grep -qx exited; then
-      return 0 # Success.
-    fi
+	set +x
+	for i in $( # Wait up to 60s.
+		seq 60
+	); do
+		if systemctl show snapd.seeded.service --value --property SubState | grep -qx exited; then
+			return 0 # Success.
+		fi
 
-    sleep 1
-  done
+		sleep 1
+	done
 
-  echo "snapd not seeded after ${i}s"
-  return 1 # Failed.
+	echo "snapd not seeded after ${i}s"
+	return 1 # Failed.
 )
 
 cleanup() {
-    echo ""
-    if [ "${FAIL}" = "1" ]; then
-        echo "Test failed"
-        exit 1
-    fi
+	echo ""
+	if [ "${FAIL}" = "1" ]; then
+		echo "Test failed"
+		exit 1
+	fi
 
-    echo "Test passed"
-    exit 0
+	echo "Test passed"
+	exit 0
 }
 
 FAIL=1
@@ -32,14 +34,7 @@ trap cleanup EXIT HUP INT TERM
 # Wait for snapd seeding
 waitSnapdSeed
 
-# Configure to use the proxy
-curl -s http://canonical-lxd.stgraber.org/config/snapd.sh | sh
-
 # Install LXD
-while [ -e /usr/bin/lxd ]; do
-    apt-get remove --purge --yes lxd lxd-client lxcfs liblxc1
-done
-apt-get remove --purge cloud-init --yes
 snap remove lxd || true
 snap install lxd --channel=latest/edge
 lxd waitready --timeout=300
@@ -51,14 +46,14 @@ lxc network create lxdbr0
 lxc profile device add default eth0 nic network=lxdbr0 name=eth0
 
 if [ "${1}" = "nvidia" ]; then
-    # Enable SR-IOV
-    /usr/lib/nvidia/sriov-manage -e ALL
+	# Enable SR-IOV
+	/usr/lib/nvidia/sriov-manage -e ALL
 
-    # Confirm GPU is online
-    nvidia-smi
+	# Confirm GPU is online
+	nvidia-smi
 
-    # Disable MIG if enabled
-    nvidia-smi -mig 0
+	# Disable MIG if enabled
+	nvidia-smi -mig 0
 fi
 
 # LXD resource API
@@ -66,11 +61,11 @@ lxc info --resources
 
 # Launch test instances
 for i in $(seq 1 4); do
-    lxc init images:ubuntu/20.04/cloud "v${i}" --vm -c security.secureboot=false
-    if [ "${1}" = "nvidia" ]; then
-        lxc config device add "v${i}" vgpu gpu gputype=mdev pci=0000:07:00.0 mdev=nvidia-468
-    fi
-    lxc start "v${i}"
+	lxc init ubuntu:20.04 "v${i}" --vm -c security.secureboot=false
+	if [ "${1}" = "nvidia" ]; then
+		lxc config device add "v${i}" vgpu gpu gputype=mdev pci=0000:07:00.0 mdev=nvidia-468
+	fi
+	lxc start "v${i}"
 done
 
 # Wait for them to start and list
@@ -78,12 +73,12 @@ sleep 30
 lxc list
 
 if [ "${1}" = "nvidia" ]; then
-    # Validate NVIDIA vGPU
-    lxc exec v4 -- apt-get update
-    lxc exec v4 -- apt-get install --no-install-recommends --yes build-essential wget pciutils linux-headers-virtual
-    lxc exec v4 -- wget -6 http://canonical-lxd.stgraber.org/nvidia/v14.0/nvidia-guest.deb
-    lxc exec v4 -- apt-get install --yes /root/nvidia-guest.deb
-    lxc exec v4 -- nvidia-smi
+	# Validate NVIDIA vGPU
+	lxc exec v4 -- apt-get update
+	lxc exec v4 -- apt-get install --no-install-recommends --yes build-essential wget pciutils linux-headers-virtual
+	lxc exec v4 -- wget -6 http://canonical-lxd.stgraber.org/nvidia/v14.0/nvidia-guest.deb
+	lxc exec v4 -- apt-get install --yes /root/nvidia-guest.deb
+	lxc exec v4 -- nvidia-smi
 fi
 
 FAIL=0
