tests/storage-disks-vm: Move long name tests
This is done to avoid previously set project restrictions to impact long name tests

Signed-off-by: hamistao <pedro.ribeiro@canonical.com>

diff --git a/tests/storage-disks-vm b/tests/storage-disks-vm
--- a/tests/storage-disks-vm
+++ b/tests/storage-disks-vm
@@ -109,6 +109,73 @@ waitInstanceReady v1
 lxc exec v1 -- ls -l /mnt/foo1
 lxc stop -f v1
 
+# Check adding a disk with a source path that is allowed that symlinks to another allowed source path isn't
+# allowed at start time.
+lxc config device set v1 d1 source="${testRoot}/allowed1/not-allowed2"
+! lxc start v1 || false
+
+# Check relative symlink inside allowed parent path is allowed.
+lxc config device set v1 d1 source="${testRoot}/allowed1/foolink" path=/mnt/foolink
+lxc start v1
+waitInstanceReady v1
+[ "$(lxc exec v1  -- stat /mnt/foolink -c '%u:%g')" = "65534:65534" ] || false
+lxc stop -f v1
+
+# Check usage of raw.idmap is restricted.
+! lxc config set v1 raw.idmap="both 1000 1000" || false
+
+# Allow specific raw.idmap host UID/GID.
+lxc project set restricted restricted.idmap.uid=1000
+! lxc config set v1 raw.idmap="both 1000 1000" || false
+! lxc config set v1 raw.idmap="gid 1000 1000" || false
+lxc config set v1 raw.idmap="uid 1000 1000"
+
+lxc project set restricted restricted.idmap.gid=1000
+lxc config set v1 raw.idmap="gid 1000 1000"
+lxc config set v1 raw.idmap="both 1000 1000"
+
+# Check conflict detection works.
+! lxc project unset restricted restricted.idmap.uid || false
+! lxc project unset restricted restricted.idmap.gid || false
+
+# Check single entry raw.idmap has taken effect on disk share.
+lxc config device set v1 d1 source="${testRoot}/allowed1" path=/mnt
+lxc start v1 || (lxc info --show-log c1 ; false)
+waitInstanceReady v1
+[ "$(lxc exec v1  -- stat /mnt/foo1 -c '%u:%g')" = "1000:1000" ] || false
+[ "$(lxc exec v1  -- stat /mnt/foo2 -c '%u:%g')" = "65534:65534" ] || false
+
+# Check security.secureboot setting is applied to running VM at next start up.
+if lxc exec v1 -- mount | grep -qwF /boot/efi; then
+  lxc exec v1 -- mokutil --sb-state | grep -Fx "SecureBoot enabled"
+  lxc profile set default security.secureboot=false
+  lxc restart -f v1
+  waitInstanceReady v1
+  lxc exec v1 -- mokutil --sb-state | grep -Fx "SecureBoot disabled"
+fi
+
+# Remove disk device restrictions
+lxc stop -f v1
+lxc config device remove v1 d1
+lxc project unset restricted restricted.devices.disk
+lxc project unset restricted restricted.devices.disk.paths
+lxc project unset restricted restricted
+
+if hasNeededAPIExtension disk_io_bus; then
+  # Add a NVMe disk and check if a NVMe controller is added to the VM
+  lxc config device add v1 nvme-ssd disk source="${loopdev}" io.bus=nvme
+  lxc start v1
+  waitInstanceReady v1
+  if ! lxc exec v1 -- sh -c 'command -v lspci'; then
+    lxc exec v1 -- apt-get update
+    lxc exec v1 -- apt-get install --no-install-recommends -y pciutils
+  fi
+  lxc exec v1 -- lspci | grep -F "QEMU NVM Express Controller"
+else
+  echo 'Skipping NVME test due to missing extension: "disk_io_bus"'
+fi
+
+
 # Check adding a disk to a vm with a long name (max 63) and slash to test possible problems with long socket paths or long qemu device tags
 LONG_DEVICE_NAME="device-/-with-very-long-name-and-4-qemu-property-handling-test_"
 DEVICE_HOTPLUG="1"
@@ -164,76 +231,11 @@ if [ "${DEVICE_HOTPLUG}" = "1" ]; then
       ! lxc exec v2 -- mountpoint /mnt/bar2 || false # Just tests for mountpoint disconnected, not unmount.
   fi
 fi
-lxc delete -f v2
 
-# Check adding a disk with a source path that is allowed that symlinks to another allowed source path isn't
-# allowed at start time.
-lxc config device set v1 d1 source="${testRoot}/allowed1/not-allowed2"
-! lxc start v1 || false
-
-# Check relative symlink inside allowed parent path is allowed.
-lxc config device set v1 d1 source="${testRoot}/allowed1/foolink" path=/mnt/foolink
-lxc start v1
-waitInstanceReady v1
-[ "$(lxc exec v1  -- stat /mnt/foolink -c '%u:%g')" = "65534:65534" ] || false
-lxc stop -f v1
-
-# Check usage of raw.idmap is restricted.
-! lxc config set v1 raw.idmap="both 1000 1000" || false
-
-# Allow specific raw.idmap host UID/GID.
-lxc project set restricted restricted.idmap.uid=1000
-! lxc config set v1 raw.idmap="both 1000 1000" || false
-! lxc config set v1 raw.idmap="gid 1000 1000" || false
-lxc config set v1 raw.idmap="uid 1000 1000"
-
-lxc project set restricted restricted.idmap.gid=1000
-lxc config set v1 raw.idmap="gid 1000 1000"
-lxc config set v1 raw.idmap="both 1000 1000"
-
-# Check conflict detection works.
-! lxc project unset restricted restricted.idmap.uid || false
-! lxc project unset restricted restricted.idmap.gid || false
-
-# Check single entry raw.idmap has taken effect on disk share.
-lxc config device set v1 d1 source="${testRoot}/allowed1" path=/mnt
-lxc start v1 || (lxc info --show-log c1 ; false)
-waitInstanceReady v1
-[ "$(lxc exec v1  -- stat /mnt/foo1 -c '%u:%g')" = "1000:1000" ] || false
-[ "$(lxc exec v1  -- stat /mnt/foo2 -c '%u:%g')" = "65534:65534" ] || false
-
-# Check security.secureboot setting is applied to running VM at next start up.
-if lxc exec v1 -- mount | grep -qwF /boot/efi; then
-  lxc exec v1 -- mokutil --sb-state | grep -Fx "SecureBoot enabled"
-  lxc profile set default security.secureboot=false
-  lxc restart -f v1
-  waitInstanceReady v1
-  lxc exec v1 -- mokutil --sb-state | grep -Fx "SecureBoot disabled"
-fi
-
-if hasNeededAPIExtension disk_io_bus; then
-  # Remove disk device restrictions and add a NVMe disk
-  lxc stop -f v1
-  lxc config device remove v1 d1
-  lxc project unset restricted restricted.devices.disk
-  lxc project unset restricted restricted.devices.disk.paths
-  lxc project unset restricted restricted
-
-  # Add a NVMe disk and check if a NVMe controller is added to the VM
-  lxc config device add v1 nvme-ssd disk source="${loopdev}" io.bus=nvme
-  lxc start v1
-  waitInstanceReady v1
-  if ! lxc exec v1 -- sh -c 'command -v lspci'; then
-    lxc exec v1 -- apt-get update
-    lxc exec v1 -- apt-get install --no-install-recommends -y pciutils
-  fi
-  lxc exec v1 -- lspci | grep -F "QEMU NVM Express Controller"
-else
-  echo 'Skipping NVME test due to missing extension: "disk_io_bus"'
-fi
 
 echo "==> Cleanup"
 lxc delete -f v1
+lxc delete -f v2
 lxc project switch default
 lxc project delete restricted
 lxc storage delete default
