tests/vm: Test exit codes for a signaled process
Do this instead of testing a clean stop since a clean stop can be
unpredictable.

Signed-off-by: hamistao <pedro.ribeiro@canonical.com>

diff --git a/tests/vm b/tests/vm
--- a/tests/vm
+++ b/tests/vm
@@ -21,15 +21,20 @@ if ! echo "${LXD_SNAP_CHANNEL}" | grep -qE '^4\.0/'; then
     lxc start vm1
     waitInstanceBooted vm1
 
-    echo "==> Test lxc exec exit code when stopping the VM cleanly"
-    (sleep 5 && lxc stop vm1) &
-    lxc exec vm1 -- sleep 60 || exitCode=$?
-    [ "${exitCode:-0}" -eq 129 ]
-    wait $!
+    echo "==> Test getting the correct exit code for a signaled process"
+    # Signaling the process spawned by lxc exec and checking its exit code.
+    # Simulates what can happen if the container stops in the middle of lxc exec.
+    for signal in SIGTERM SIGHUP SIGTERM; do
+        echo "==> Test getting the correct exit code when sending ${signal} to an exec'ed process"
+        code="$(kill -l "${signal}")"
+        # killall is not included in minimal images so we use escaping to combine pgrep and kill.
+        (sleep 5 && lxc exec vm1 -- bash -c "kill -s ${signal} \$(pgrep sleep)") &
+        lxc exec vm1 -- sleep 60 || exitCode=$?
+        # Check exit code, should be 128 plus signal number, 1 for SIGHUP, 9 for SIGKILL and 15 for SIGTERM.
+        [ "${exitCode:-0}" -eq $((128 + code)) ]
+    done
 
     echo "==> Test lxc exec exit code when stopping the VM abruptly"
-    lxc start vm1
-    waitInstanceBooted vm1
     (sleep 5 && lxc stop -f vm1) &
     lxc exec vm1 -- sleep 60 || exitCode=$?
     [ "${exitCode:-0}" -eq 129 ]
