github: tweak `actions/image-setup` connectivity check
Only get the runner's public IP if the connection failed.

Signed-off-by: Simon Deziel <simon.deziel@canonical.com>

diff --git a/.github/actions/image-setup/action.yml b/.github/actions/image-setup/action.yml
--- a/.github/actions/image-setup/action.yml
+++ b/.github/actions/image-setup/action.yml
@@ -16,16 +16,11 @@ runs:
       shell: bash
       run: |
         set -eux
-
-        # Try to get own public IP
-        MY_PUBLIC_IP="$(curl --silent --max-time 5 https://api.ipify.org || true)"
-        [ "${MY_PUBLIC_IP}" = "" ] && exit 0
         command -v nc || exit 0
 
         # Test connectivity to SFTP server
         SUCCESS="false"
         for attempt in 1 2 3 4 5; do
-          echo "Try to connect from ${MY_PUBLIC_IP}..."
           if nc -w 5 -zv images.lxd.canonical.com 922; then
             SUCCESS="true"
             break
@@ -33,7 +28,11 @@ runs:
         done
 
         # Fail the job if the connection did not succeed.
-        [ "${SUCCESS}" = "true" ]
+        [ "${SUCCESS}" = "true" ] && exit 0
+
+        # Try to get own public IP
+        MY_PUBLIC_IP="$(curl --silent --max-time 5 https://api.ipify.org || true)"
+        echo "Unable to connect from ${MY_PUBLIC_IP:-"unknown"}!"
 
     - name: Install dependencies
       shell: bash
