github: fix yaml syntax errors in workflow files
Signed-off-by: Simon Deziel <simon.deziel@canonical.com>

diff --git a/.github/workflows/commits.yml b/.github/workflows/commits.yml
--- a/.github/workflows/commits.yml
+++ b/.github/workflows/commits.yml
@@ -10,12 +10,12 @@ jobs:
     name: Branch target
     runs-on: ubuntu-22.04
     steps:
-    - name: Check branch target
-      env:
-        TARGET: ${{ github.event.pull_request.base.ref }}
-      run: |
-        set -x
-        [ "${TARGET}" = "main" ] && exit 0
+      - name: Check branch target
+        env:
+          TARGET: ${{ github.event.pull_request.base.ref }}
+        run: |
+          set -x
+          [ "${TARGET}" = "main" ] && exit 0
 
-        echo "Invalid branch target: ${TARGET}"
-        exit 1
+          echo "Invalid branch target: ${TARGET}"
+          exit 1
